### ISSUE TITLE
v12 Causes inventory changes to fire off a message for every connected user

### ISSUE THREAD

**Issue by GambetTV** [Larkinabout/fvtt-change-log#17]
This is in v12.331 of Foundry, on DnD5e 3.3.1, v1.1.0 of ChangeLog.

Certain actions, such as deleting an inventory item, changing the number of spell slots, but not other things, causes Changelog to send 1 message per player connected. It's hidden from the players, but it clutters up chat for the DM.

![image](https://github.com/user-attachments/assets/d950172c-e9f0-440c-aa4d-84c965b40263)

**Comment by mhilbrunner** [comment]
@GambetTV As I got no response on a [PR](https://github.com/Larkinabout/fvtt-change-log/pull/15) so far and the author seem understandably busy, I fixed this and a few other issues in a fork for now: https://github.com/mhilbrunner/fvtt-change-log

You should be able to install that using the URL:
`https://github.com/mhilbrunner/fvtt-change-log/releases/latest/download/module.json`

Ping me if you run into any issues. Note that I made two small modifications for my own sake:
- The chat messages are a bit more minimal, posted with the modified actor as speaker, which removes a text line from the size
- There is an (optional) setting to only log changes for player-owned actors

@Larkinabout Happy holidays and thanks for the module, feel free to take any of the changes I made in my fork :) Also happy to PR them if wanted.

**Comment by GambetTV** [comment]
10 out of 10 my dude. Thank you very much, this has cleaned up my chat logs so nicely!

**Comment by Larkinabout** [comment]
> @Larkinabout Happy holidays and thanks for the module, feel free to take any of the changes I made in my fork :) Also happy to PR them if wanted.

Go ahead and PR them and I'll see if I can get to them all next week.

**Comment by mhilbrunner** [comment]
@Larkinabout Thank you! Done, I hope I didn't miss anything while extracting the changes and splitting them up into PRs.

**Comment by GambetTV** [comment]
@mhilbrunner Okay so I finally used this during a combat encounter in a session, and noticed that it is not keeping track of HP anymore. It's keeping track of spell slots and things like that, but for whatever reason whether it's a PC or an NPC, it's not firing anything off. I checked the settings and on player-owned actors and regardless of how it's set it's still not working.

**Comment by mhilbrunner** [comment]
Thats weird. It works with me for SWADE Wounds, but there may be something different about 5E HP. You may want to revert to the original module, as (some of) the changes should land there soon.
